export const PRESENT = "present";

export const EXPERIENCES = [
  {
    start: "Jan 2020",
    end: PRESENT,
    title: "Android Engineer",
    company: "Huawei Technologies",
    companyLogo:
      "htt" +
      "ps://consumer-res.huawei" +
      ".com/etc/designs/huawei-cbg-site/clientlib-campaign-v4/common-v4/images/logo.svg",
    location: "Dubai, UAE",
    website: "htt" + "ps://ww" + "w.huawei" + ".com/en",
    technologies: [
      "Android",
      "HarmonyOS",
      "Kotlin",
      "Java",
      "React-Native",
      "Huawei Mobile Services (HMS)",
      "Google Mobile Services (GMS)",
      "Firebase",
      "Javascript",
      "CSS",
      "HTML",
      "Laravel",
      "PHP",
      "Git",
      "Photoshop",
    ],
    
    experiences: [
      "Fully Integrated HMS (Huawei Mobile services) into large scale native apps (java and kotlin) and react-native apps like Carrefour, emirates auction, talabat, UbyEmaar, the dubai mall, virgin mobile and more",
      "Developed a fitness app for huawei harmonyOs smart watch",
      "Created android library to ease Huawei Site kit integration",
      "Created react-native library to ease Huawei maps integration",
      "Created azure devOps pipelines to deploy apps to huawei AppGallery",
      "Provided onsite and remote technical support for Huawei mobile services (as well as google mobile services)",
      "Created a web app using Angular, and backend service using laravel/lumen",
      "Created and maintained an app downloader and installer app using Kotlin, based on the MVVM architecture utilizing latest Android technologies",
      "Edited graphic designs using Photoshop",
      "Published technical articles and tutorials",
    ],
  },
  {
    start: "Nov 2018",
    end: "Oct 2019",
    title: "Full stack web developer",
    company: "Algebratec",
    companyLogo:
      "htt" +
      "ps://ww" +
      "w.algebratec" +
      ".com/wp-content/uploads/elementor/thumbs/logo_white-od57qsmy4852r4rrvaglwo96w34i4ivi4nrr2g1c3k.png",
      location: "Constantine, Algeria",
    website: "htt" + "p://www." + "algebratec" + ".com",
    technologies: [
      "Laravel/Lumen",
      "Angular",
      "nodejs",
      "jQuery",
      "Swagger-ui",
      "Angular Material",
      "Bootstrap",
      "Animate.css",
      "nativescript",
      "react",
      "Laravel/passport",
      "Git",
    ],
    experiences: [
      "Helped the team managing our clients by creating a dashboard using Angular.",
      "Create an API service with Laravel/Lumen implementing token authentication and analytics.",
      "Built 6 landing pages with Angular utilizing Angular material, Bootstrap and bulmaCSS.",
      "Accelerated the development of our websites 3 times by creating a special angular project structure and writing NodeJs scripts that helped share one codebase between them.",
      "Collected data from 3 hotel websites by creating a scraping tool that I built using Goutte/php.",
      "Eased the integration of our hotel booking API by our clients through a documentation page that I created using React and Swagger-ui.",
      "Designed and built our company's new website with wordpress and Elementor.",
      "Designed a demo website for hotel including booking with Wordpress and Angular.",
      "Managed and Organized the workflow of the projects with Trello, and used GIT for versioning.",
      "Customized a NativeScript project to hold multiple apps at once sharing the same business logic.",
    ],
  },
  {
    start: "Mar 2016",
    end: "Sep 2019",
    title: "Android Developer",
    company: "Personal",
    companyLogo: "",
    location: "Algeria",
    website: "",
    technologies: [
      "Android",
      "Java",
      "Google Mobile Services",
      "Firebase",
      "LibGDX",
      "Laravel/Lumen",
      "PHP",
      "nodejs",
      "Photoshop",
    ],
    experiences: [
      "Created 25+ android apps for different purposes.",
      "Developed the apps mainly in JAVA mastering all of its features.",
      "Integrated google auth, maps SDK and the Drive API for multiple apps.",
      "Used the LibGDX framework to create two games.",
      "Created a RESTful API service for an app with Laravel (PHP).",
      "Implemented Firebase as a backend for two apps.",
      "Created modern designs following google’s material design guidelines.",
      "Used the MVVM architecture utilizing data binding and JetPack components.",
    ],
  },
];
